- .github/workflows/ci.yml
- Cargo.toml
Currently,
- `rpm-rs` depends on `rsa-der ^0.3.0`
- `rsa-der 0.3.0` depends on `simple_asn1 ^0.6`
- `simple_asn1 0.6.2` depends on `time ^0.3`
- `time 0.3.14` specifies MSRV `1.59.0`
This commit fixes the following error with Rust 1.57.0 (occurs in CI):
> error: package `time v0.3.14` cannot be built because it requires rustc 1.59.0 or newer, while the currently active rustc version is 1.57.0
> Set MSRV to 1.59.0 in Cargo.toml

- src/compat_tests.rs
`cargo test --features test-with-podman` currently fails because of the removal of repository mirrors for deprecated CentOS 8.
This PR fixes these tests by replacing CentOS 8 with CentOS Streams, and also update other container images used by the tests.
- Fix test-with-podman (centos 8 deprecated)
- test-with-podman: update images
- Remove extra space
> test-with-podman: Update container images

- .github/workflows/ci.yml
- src/lib.rs
- src/rpm/builder.rs
- src/rpm/headers/header.rs
- src/rpm/package.rs
- src/tests.rs
After #34 there were a few warnings. This fixes up the remainder.
The annotations are only required for the pub(crate) functions. I've manually tested with each feature enabled that this compiles, though at some point we should consider a matrix.
> Fix up remaining warnings in no-default-features

- src/rpm/builder.rs
This updates rpm-rs to not universally add /bin/sh as a required dependency.
I want to use rpm-rs (via cargo-generate-rpms) to create RPMs that don't depend on /bin/sh , as I want to then install the RPMs I'm producing into a container, and I don't want a shell and its dependencies installed in the container.
I can't find any rationale for the existing behaviour - it was added in https://github.com/rpm-rs/rpm-rs/commit/ecbcdabea59af48b5f9a6a915c2242a7d8a6d0c5#diff-43fb48f0415ccc8ae772c068cc4bc8717f04a0e93a4113396ce0b48deddd9af6.
> Don't add /bin/sh as a dependency

- .github/pull_request_template.md
- src/rpm/headers/types.rs
Adds a pull request template for github, to provide a standard set of contextual information to ease the review process and avoid delays due to information retrieval.
> gh: add pull request template

- CHANGELOG.md
- src/rpm/package.rs
- src/tests.rs
Remove the helper function `get_file_ima_signature_length` after a discussion with RPM developers - the tag should be considered obsolete and therefore we ought not to encourage its use with a helper.
https://github.com/rpm-software-management/rpm/commit/b7e9a60370d910febbe8c69e2d2cac7512051eb3
- 🦣 Legacy
- 🪣 Misc
> Remove get_file_ima_signature_length()

- CHANGELOG.md
- README.md
- src/compat_tests.rs
- src/rpm/builder.rs
- src/rpm/package.rs
- src/tests.rs
- 🦚 Feature
Adds optional fields vendor and repository to RPMBuilder. 
This allows for proper component governance and attribution of rpms.
Tests
Added vendor and repository fields to the create full rpm tests and passes as expected.
> Add optional fields vendor and repository to RPMBuilder. 

- .github/workflows/ci.yml
- src/rpm/builder.rs
If both `with-file-async-tokio` and `with-file-async-async-std` are both specified, then prefer tokio over async-std.
- 🩹 Bug Fix
Add some feature flag gating that prevents duplicate definitions if --all-features is defined.
> Allow `cargo build --all-features` to work by preferring tokio

- CHANGELOG.md
- src/rpm/package.rs
- src/tests.rs
Adds a helper method that avoids making the user do buffer management for common use cases.
- 🦚 Feature
> Added RPMPackage::open()

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
Most users won't need it, and the dependencies it pulls in are very heavy.  Make it opt-in.
closes #89
> Remove async support from default features

- .github/pull_request_template.md
The current PR template is very thorough but a bit overwhelming and overkill for most contributions, slimming it down a bit might be helpful.
> Streamline pull request template

- CHANGELOG.md
- src/errors.rs
- src/rpm/headers/lead.rs
- src/rpm/headers/mod.rs
Lead has been deprecated upstream for a long time and the docs suggest not to read it.  There is a plan to stop populating its fields entirely, so we should stop trying to validate them.
closes #78
- 🦣 Legacy
See the references attached to the issue
> Remove "Lead" from the public API and stop checking its fields

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/rpm/builder.rs
- src/rpm/package.rs
Incremental improvement towards making an empty package built by rpm-r more similar to one created by rpmbuild
> Automatically set BUILDHOST and tag and add COOKIE tag

- src/constants.rs
- src/rpm/headers/header.rs
There's no need for Tag to be a blanket impl when we know that there are only 2 implementers, and TagName isn't useful when you can just implement it on Tag.
> Simplify Tag trait

- CHANGELOG.md
- Cargo.toml
- src/constants.rs
- src/errors.rs
- src/rpm/builder.rs
- src/rpm/headers/header.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
- src/tests.rs
> Create & verify PAYLOADDIGEST, PAYLOADDIGESTALT

- CHANGELOG.md
- src/constants.rs
- src/rpm/headers/header.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
- src/tests.rs
- tests/parsing.rs
The motivating reason is that RPM repo metadata has an element in the XML which declares the start and end boundaries of the header, so we need to expose some way to get that.
> Add a function for getting the boundaries between of the components of the package

- CHANGELOG.md
- src/constants.rs
- src/rpm/builder.rs
- src/rpm/headers/header.rs
- src/rpm/headers/signature_builder.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
- src/tests.rs
- tests/compat.rs
Use 64bit file tags to support file sizes >4gb.  All versions of `rpm` starting with 4.6.0 (circa 2008) support and look for the 64bit tags by default so there is little reason to support the fallback logic.
- 🩹 Bug Fix
- 🦚 Feature
- 🦣 Legacy
closes #65
> Support files >4gb, default to 64bit tag sizes for tag-related data

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/rpm/builder.rs
- src/rpm/compressor.rs
- src/rpm/package.rs
- src/tests.rs
- tests/compat.rs
- tests/parsing.rs
- tests/signatures.rs
> Add parsing Compressor and add compress feature

- CHANGELOG.md
- src/errors.rs
- src/rpm/headers/header.rs
- src/tests.rs
Unfortunately it is common for certain tags to be present in the wrong header, so there are many packages in the wild which rpm-rs would fail to parse. Additionally any packages built with brand-new versions of rpmbuild which contain tags not listed in our list of constants would fail.
In either case, we ought to be a bit more tolerant. Users should be able to parse the RPMs and do basic things with them even if we don't provide the ability to work with the unknown parts of the header.
This PR turns the `tag` into a standard u32 rather than an enum and removes the `InvalidTag` error variant.  It retains the other properties of `Header<T>` using the `PhantomData` zero-sized-type.  Additionally it adjusts the `Debug` trait impl to continue showing the tag names as before, rather than the …
> Make parsing more robust in the face of unknown or unexpected tags

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/rpm/builder.rs
- src/rpm/headers/header.rs
- src/rpm/headers/lead.rs
- src/rpm/package.rs
- src/tests.rs
I have had suspicions that this library may not be a good fit for async use, and have finally gotten around to checking whether they are accurate.
I wrote some executables to test
* building packages
* signing packages
* parsing packages
* verifying digests / signatures
Since async runtimes are all about latency and non-blocking cooperative multitasking, I tried to find the most realistic worst-case scenarios.  I wrote a script that printed a list of the top 20 largest packages in Fedora and downloaded a few of those (ranging from 100mb to 2.9gb).  I also tested normal sized packages like `zlib` and `sqlite` but while the magnitude was smaller the relative pattern was basically the same with those. For the "build" tests I extracted the contents of those packages and then used `rpm-rs` to …
> Delete async feature - this crate is not actually async-safe

- CHANGELOG.md
- Cargo.toml
- src/constants.rs
- src/errors.rs
- src/rpm/builder.rs
- src/rpm/headers/header.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
> Use proper flag semantics instead of passing around raw integers

- CHANGELOG.md
- src/rpm/package.rs
- tests/parsing.rs
> Make get_payload_compressor() return CompressionType::None if the tag doesn't exist

- src/rpm/package.rs
In PR: https://github.com/rpm-rs/rpm/pull/138 forgot to delete one method `RPMPackage::write_async`.
> Removed last async method

- Cargo.toml
- src/rpm/signature/pgp.rs
pgp v0.9 causes the following future incompatibility warning:
```
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, nom v4.2.3
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```
> Update pgp to v0.10

- CHANGELOG.md
- src/lib.rs
- src/rpm/builder.rs
Depends on #152
Relevant issue: #117
In v0.12 it may be worth to remove the `build_time` method altogether and instead set build time to `source_date` if it was set.
> Add source_date method

- CHANGELOG.md
- src/rpm/builder.rs
- src/rpm/package.rs
Purpose: Allows you to debug which library, and which version of the library the package was built with
> Add RPMTAG_RPMVERSION tag to headers

- CHANGELOG.md
- Cargo.toml
- README.md
- src/errors.rs
- src/rpm/builder.rs
- src/rpm/headers/header.rs
- src/rpm/headers/signature_builder.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
- src/tests.rs
- tests/signatures.rs
This change adds support for setting the RPMTAG_FILECAPS header to add capabilities to the files packaged in the rpm.
> Add support for setting RPMTAG_FILECAPS header

- CHANGELOG.md
- src/rpm/headers/types.rs
- src/tests.rs
- tests/compat.rs
- Sometimes not standard rpm package container symbolic link, it is better to recognize them.
- `FileMode::file_type` is public, so it is better to make the const `REGULAR_FILE_TYPE` `DIR_FILE_TYPE` `SYMBOLIC_LINK_FILE_TYPE` public also to ease usage.
> add symbolic link file type support

- CHANGELOG.md
- src/rpm/builder.rs
- src/tests.rs
Currently, when building a package with `PackageBuilder`, the same string `desc` is used for both `Summary` and `Description`:
https://github.com/rpm-rs/rpm/blob/bb5c1ea3b598ebd3e03969508057ab9e1d7ab359/src/rpm/builder.rs#L794-L802
However:
- `Summary` is meant to be a _"brief, one-line summary of the package"_ (rpmlint requires a short string which does not end with a dot).
- `Description` should be a  _"full description of the software packaged in the RPM. This description can span multiple lines and can be broken into paragraphs."_ And rpmlint requires a string which does end with a dot.
In this PR, I rename the last parameter of `PackageBuilder::new()` from `desc` to `summary`, and I add a setter `description` to the package builder.
The default value for `Description` is the summary, …
> PackageBuilder: both summary and description

- CHANGELOG.md
- README.md
- src/rpm/headers/types.rs
- src/tests.rs
- tests/compat.rs
Add method `is_no_replace` to `FileOptionsBuilder`, used to set the `%config(noreplace)` flag on a file
Closes #186
> Add %config(noreplace) file attribute to builder

- CHANGELOG.md
- src/rpm/headers/header.rs
- src/rpm/package.rs
- src/tests.rs
- tests/parsing.rs
Support all file-related functions for a case where an RPM is free of files.
> Unify file-related information under FileEntry (get_file_entries)

- CHANGELOG.md
- src/constants.rs
- src/rpm/headers/header.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
- src/tests.rs
> Fixup changelog and other small things

- CHANGELOG.md
- src/errors.rs
- src/rpm/signature/pgp.rs
Uses a different approach than the ones in comments of #191. Most errors do not need to be boxed, and introducing two error variants instead of having one very generic one (with static details) ends up not being too bad.
> Make Error Send + Sync (fixes #191)

- CHANGELOG.md
- Cargo.toml
- src/errors.rs
- src/rpm/filecaps.rs
- src/rpm/headers/types.rs
- src/rpm/mod.rs
- src/tests.rs
Referring to capctl crate，implemented a simple filecaps that can validate caps text and run on non-linux platform.
> Use a minimal filecaps instead of capctl crate that can run on non-linux platform

- CHANGELOG.md
And fix some changelogs that were in the wrong place
> 0.13.1 release

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/constants.rs
- src/rpm/builder.rs
- src/rpm/headers/types.rs
- src/rpm/package.rs
- src/tests.rs
- tests/compat.rs
I'm trying to split the irrelevant stuff out of my other PRs and get it merged a bit sooner, while I'm working out a few details on the more complex stuff.  Making those PRs smaller is also nice.
The reason for all the little features is that the gaps were encountered in the process of writing new tests.
I went through some effort to make sure the commits are split cleanly as opposed to the other PRs where they got mashed up a bit.
> Improve documentation and add a few small features and fixes

- CHANGELOG.md
- src/rpm/package.rs
> Expose PackageMetadata::write publicly

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- src/rpm/package.rs
- src/rpm/signature/pgp.rs
> Update dependencies & new release

- tests/compat.rs
CentOS Stream 8 is EOL now, the repos are taken down.
> Use almalinux 8 instead of CentOS Stream 8 for tests

- src/rpm/filecaps.rs
```
warning: this manual char comparison can be written more succinctly
--> src/rpm/filecaps.rs:120:37
|
120 |         let index = match part.find(|c| c == '+' || c == '-' || c == '=') {
|                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using an array of `char`: `['+', '-', '=']`
```
> Fix clippy warning:

- CHANGELOG.md
- src/rpm/headers/header.rs
The change makes a measurable performance gain for debuginfod-rs:
```
Before:
Time (mean ± σ):      2.322 s ±  0.042 s    [User: 25.047 s, System: 4.994 s]
After:
Time (mean ± σ):      2.269 s ±  0.023 s    [User: 24.264 s, System: 5.174 s]
1.02 ± 0.02 times faster than debuginfod-rs-before
```
> Speed up parse_header of the binary IndexData

- src/rpm/package.rs
I was able to measure a difference for debuginfod-rs:
```
Time (mean ± σ):      2.303 s ±  0.017 s    [User: 25.220 s, System: 5.214 s]
Range (min … max):    2.272 s …  2.327 s    10 runs
Warning: Ignoring non-zero exit code.
Benchmark 2: /tmp/after3
Time (mean ± σ):      2.298 s ±  0.028 s    [User: 24.979 s, System: 5.310 s]
Range (min … max):    2.241 s …  2.331 s    10 runs
Warning: Ignoring non-zero exit code.
Summary
/tmp/after3
1.00 ± 0.01 times faster than /tmp/before
```
> Remove extra allocation in get_file_paths

- CHANGELOG.md
- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/rpm/builder.rs
- src/rpm/compressor.rs
- src/tests.rs
This pull request adds a feature flag for every compression algorithm. All compression algorithms are all enabled by default, but can be disabled in case they are not used to reduce the amount of dependencies.
Please note: I couldn't run all the tests because some containers are not found in the registry I am using.
> Add feature flags for compression algorithms

- tests/compat.rs
centos docker image went EOL in June 2024 and do not appear to be available on hub.docker.com anymore.
This breaks tests when you don't already have an image cached on your computer.
This commit migrates to one available on quay.io
> tests: centos on docker hub went EOL

- CHANGELOG.md
- Cargo.toml
- src/rpm/builder.rs
- src/rpm/compressor.rs
- src/rpm/filecaps.rs
- src/rpm/package.rs
- src/version.rs
Note: I'm working on tests, but they will be easier to merge as part of the test overhaul PR.  In the meantime I did some manual testing for this PR.
> Add an API for reading files from the RPM payload

- src/rpm/signature/pgp.rs
- tests/compat.rs
RPM in RHEL 8 and 9 are unable to find the signing key id when signed with this the rpm crate.  Newer versions of RPM do not have this issue.
By adding a second Issuer packet which is not critical works around the old RPM deficiency.
Closes #265
> Add Issuer as regular packet during signing.

- src/rpm/builder.rs
- src/tests.rs
> Re-enable rpm_builder test on windows CI runner
