src/rpm/builder.rs, src/rpm/headers/header.rs, src/rpm/headers/types.rs, src/rpm/package.rs, src/rpm/signature/pgp.rs
Add some typo fix as well as fix some clippy warning.
=> Typo and Cleanup fix

.gitignore, src/rpm/package.rs, src/sequential_cursor.rs, src/tests.rs
1. Fix Seek&Read issue in SeqCursor
2. Fix md5 hash infinite loop when sign package
3. Add test for sign package and SeqCursor
Close #16
=> Fix packge sign issue

.github/workflows/ci.yml, src/lib.rs, src/rpm/builder.rs, src/rpm/headers/header.rs, src/tests.rs
=> Add an empty signature constructor

src/rpm/builder.rs, src/rpm/compressor.rs, src/rpm/headers/header.rs, src/rpm/headers/lead.rs, src/rpm/headers/types.rs, src/rpm/package.rs, src/rpm/signature/pgp.rs
closes #46
Eliminates a few potential sources of panic!(), improve message in cases where it is left as-is.
- 🪣 Misc
=> Inspect uses of unwrap() and expect() and improve them where possible

src/constants.rs, src/rpm/headers/header.rs, src/rpm/headers/types.rs
=> Switch constants to unsigned integers

.github/workflows/ci.yml, src/compat_tests.rs
- 🩹 Bug Fix
Closes #43
- Fix compatibility tests
- Run compatibility tests in CI
=> Fix compat tests + run in CI

Cargo.toml
Going to be the first published release on <https://crates.io>
=> release: 0.9.0-alpha.1

Cargo.toml, src/lib.rs, src/rpm/package.rs
=> release: 0.9.0

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, src/rpm/builder.rs, src/rpm/headers/header.rs, src/rpm/package.rs
=> Put build time into generated RPMs

.github/workflows/ci.yml
`actions-rs` is unmaintained: https://github.com/actions-rs/toolchain/issues/216. The PR reaplce `actions-rs` to [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain)
Result of running pipeline is here: https://github.com/ikrivosheev/rpm/pull/1
- 🪣 Misc
=> Replace action-rs to dtolnay/rust-toolchain

CHANGELOG.md, README.md, src/constants.rs, src/lib.rs, src/rpm/builder.rs, src/rpm/headers/types.rs
Add the appropriate `rpmlib()` requires to built packages.  Fixed up the README example code
- 🩹 Bug Fix
=> Fix rpmlib() requires

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/constants.rs, src/rpm/builder.rs, src/rpm/headers/header.rs, src/rpm/headers/signature_builder.rs, src/rpm/package.rs, src/sequential_cursor.rs, tests/parsing.rs
=> Add SHA256HEADER tag to signature header for built packages (and fix the verification code)

CHANGELOG.md, src/constants.rs, src/rpm/builder.rs, src/rpm/headers/types.rs, src/rpm/package.rs
=> Make fields on FileEntry and other structs public

CHANGELOG.md, src/rpm/builder.rs, src/rpm/headers/header.rs, src/rpm/headers/signature_builder.rs, src/tests.rs, tests/compat.rs
Closes #148 and fixes several clippy lints.
=> Use long sizes only for big packages

CHANGELOG.md, README.md, src/errors.rs, src/lib.rs, src/rpm/builder.rs, src/rpm/compressor.rs, src/rpm/headers/header.rs, src/rpm/headers/lead.rs, src/rpm/headers/types.rs, src/rpm/package.rs, src/rpm/signature/pgp.rs, src/rpm/signature/traits.rs, src/tests.rs, tests/compat.rs, tests/parsing.rs, tests/signatures.rs
=> Remove RPM prefix from type names

CHANGELOG.md, Cargo.toml, src/rpm/signature/pgp.rs
N/A
The release has already happened on a different branch
=> Sync 0.12.1 release

CHANGELOG.md, README.md, src/constants.rs, src/errors.rs, src/rpm/builder.rs, src/rpm/headers/types.rs, src/rpm/package.rs, src/tests.rs
- During package upgrade, this gives the new package a hook after the old package is uninstalled.
Closes #199
=> feat. Adding options for %pretrans %posttrans scriptlets

src/rpm/headers/types.rs, src/tests.rs
=> fixup. fix scriptlet string conversion impl

CHANGELOG.md, Cargo.toml
=> 0.15.1 release notes

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/rpm/signature/pgp.rs
=> pgp: bump to 0.14

CHANGELOG.md, Cargo.toml, README.md
=> 0.16.0 release

CHANGELOG.md, Cargo.toml, src/rpm/compressor.rs
- [x ] A changelog entry or entries has been added to CHANGELOG.md
- [x ] Documentation is thorough
- [ x] Test coverage is excellent and passes
=> Replace xz2 crate with liblzma crate

CHANGELOG.md, src/constants.rs, src/rpm/builder.rs, src/rpm/headers/header.rs, src/rpm/headers/lead.rs, src/rpm/package.rs, tests/signatures.rs
=> Add signature clearing functionality

CHANGELOG.md, Cargo.toml
=> 0.17.0 release

CHANGELOG.md, Cargo.toml, src/rpm/builder.rs, src/rpm/mod.rs, src/rpm/package.rs, src/rpm/payload.rs
=> Support "stripped cpio" format

CHANGELOG.md, Cargo.toml
=> Use native Rust implementations of zlib and libbz2

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/rpm/builder.rs, src/rpm/package.rs, tests/compat.rs
=> Add a configuration to PackageBuilder that can be shared between package builds

CHANGELOG.md, src/rpm/builder.rs, src/version.rs, tests/compat.rs
=> Fix NEVRA parsing

CHANGELOG.md, src/constants.rs, src/rpm/builder.rs, src/rpm/headers/types.rs, src/rpm/package.rs
=> Add sha512 payload checksum support

CHANGELOG.md, src/rpm/package.rs
=> 0.18.0 release
